"""
Social interaction integration for Prompted Town.

This module handles the integration between AI-powered conversations
and the world state. The AI engine produces ConversationOutcome objects;
this module applies those outcomes to the simulation.

Design principles:
- Clear interface between AI and simulation
- Outcomes are structured data, not free-form
- All state changes are explicit and logged
"""

from dataclasses import dataclass, field
from typing import Optional

from ..core.types import (
    EventType,
    ConversationIntent,
    Location,
    EmotionalState,
    Faction,
)
from ..core.world_state import WorldState, Event, RelationshipState
from ..core.agent_spec import AgentSpec


# =============================================================================
# CONVERSATION OUTCOME (from AI engine)
# =============================================================================

@dataclass
class DialogueTurn:
    """A single turn in a conversation."""
    speaker_id: str
    text: str
    subtext: Optional[str] = None  # What they're really thinking/feeling
    detected_intent: Optional[str] = None  # What the listener might perceive


@dataclass
class ConversationOutcome:
    """
    Structured result of an AI-powered conversation.

    The AI engine fills this out based on the conversation transcript.
    The simulation applies these values to world state.
    """
    # Participants
    initiator_id: str
    target_id: str

    # The conversation itself
    transcript: list[DialogueTurn] = field(default_factory=list)
    turn_count: int = 0

    # Relationship changes
    initiator_trust_delta: float = 0.0  # How initiator's trust in target changed
    target_trust_delta: float = 0.0     # How target's trust in initiator changed

    # Intent-specific outcomes
    recruitment_attempted: bool = False
    recruitment_successful: bool = False

    interrogation_attempted: bool = False
    information_revealed: list[str] = field(default_factory=list)

    trade_completed: bool = False
    trade_details: Optional[dict] = None

    # Suspicion and detection
    suspicion_raised: bool = False
    suspicion_amount: float = 0.0
    witnessed_by: list[str] = field(default_factory=list)

    # Emotional outcomes
    initiator_emotional_state: Optional[EmotionalState] = None
    target_emotional_state: Optional[EmotionalState] = None

    # Conversation quality/outcome
    was_positive: bool = True  # Overall tone
    was_interrupted: bool = False
    reason_ended: str = "natural"  # "natural", "interrupted", "fled", "hostile"

    def get_summary(self) -> str:
        """Generate a brief summary of the conversation outcome."""
        parts = []

        if self.recruitment_attempted:
            if self.recruitment_successful:
                parts.append("recruitment succeeded")
            else:
                parts.append("recruitment failed")

        if self.interrogation_attempted:
            if self.information_revealed:
                parts.append(f"revealed {len(self.information_revealed)} secrets")
            else:
                parts.append("revealed nothing")

        if self.suspicion_raised:
            parts.append(f"raised suspicion (+{self.suspicion_amount:.2f})")

        if self.trade_completed:
            parts.append("trade completed")

        if not parts:
            if self.was_positive:
                parts.append("friendly exchange")
            else:
                parts.append("tense exchange")

        return ", ".join(parts)


# =============================================================================
# APPLYING OUTCOMES TO WORLD STATE
# =============================================================================

def apply_conversation_outcome(
    state: WorldState,
    outcome: ConversationOutcome,
    agent_specs: dict[str, AgentSpec],
) -> list[Event]:
    """
    Apply a conversation outcome to the world state.

    This is the main integration point between AI conversations
    and the simulation state.

    Args:
        state: World state to modify
        outcome: The conversation outcome from AI engine
        agent_specs: Agent specifications for context

    Returns:
        List of events generated by applying the outcome
    """
    events = []

    # Update relationship
    rel_events = _apply_relationship_changes(state, outcome)
    events.extend(rel_events)

    # Handle recruitment
    if outcome.recruitment_attempted:
        recruit_events = _apply_recruitment_outcome(state, outcome, agent_specs)
        events.extend(recruit_events)

    # Handle interrogation
    if outcome.interrogation_attempted:
        interrog_events = _apply_interrogation_outcome(state, outcome, agent_specs)
        events.extend(interrog_events)

    # Handle suspicion
    if outcome.suspicion_raised:
        susp_events = _apply_suspicion_from_conversation(state, outcome)
        events.extend(susp_events)

    # Handle trade
    if outcome.trade_completed and outcome.trade_details:
        trade_events = _apply_trade_outcome(state, outcome)
        events.extend(trade_events)

    # Update emotional states
    _apply_emotional_changes(state, outcome)

    # Log overall conversation end event
    events.append(Event(
        tick=state.tick,
        event_type=EventType.CONVERSATION_ENDED,
        agent_id=outcome.initiator_id,
        target_id=outcome.target_id,
        details={
            "turn_count": outcome.turn_count,
            "was_positive": outcome.was_positive,
            "reason_ended": outcome.reason_ended,
            "summary": outcome.get_summary(),
        },
        narrative=f"Conversation between {outcome.initiator_id} and {outcome.target_id} ended: {outcome.get_summary()}",
    ))

    # Log events to state
    for event in events:
        state.log_event(event)

    return events


def _apply_relationship_changes(
    state: WorldState,
    outcome: ConversationOutcome,
) -> list[Event]:
    """Apply trust/relationship changes from conversation."""
    events = []

    rel = state.get_relationship(outcome.initiator_id, outcome.target_id)

    # Apply trust changes
    if outcome.initiator_trust_delta != 0:
        old_trust = rel.get_trust(outcome.initiator_id, outcome.target_id)
        rel.adjust_trust(outcome.initiator_id, outcome.target_id, outcome.initiator_trust_delta)
        new_trust = rel.get_trust(outcome.initiator_id, outcome.target_id)

        if abs(outcome.initiator_trust_delta) >= 0.1:
            events.append(Event(
                tick=state.tick,
                event_type=EventType.CONVERSATION_ENDED,
                agent_id=outcome.initiator_id,
                target_id=outcome.target_id,
                details={
                    "trust_change": outcome.initiator_trust_delta,
                    "old_trust": old_trust,
                    "new_trust": new_trust,
                    "direction": f"{outcome.initiator_id} → {outcome.target_id}",
                },
                narrative=f"{outcome.initiator_id}'s trust in {outcome.target_id}: {old_trust:.2f} → {new_trust:.2f}",
            ))

    if outcome.target_trust_delta != 0:
        old_trust = rel.get_trust(outcome.target_id, outcome.initiator_id)
        rel.adjust_trust(outcome.target_id, outcome.initiator_id, outcome.target_trust_delta)
        new_trust = rel.get_trust(outcome.target_id, outcome.initiator_id)

        if abs(outcome.target_trust_delta) >= 0.1:
            events.append(Event(
                tick=state.tick,
                event_type=EventType.CONVERSATION_ENDED,
                agent_id=outcome.target_id,
                target_id=outcome.initiator_id,
                details={
                    "trust_change": outcome.target_trust_delta,
                    "old_trust": old_trust,
                    "new_trust": new_trust,
                    "direction": f"{outcome.target_id} → {outcome.initiator_id}",
                },
                narrative=f"{outcome.target_id}'s trust in {outcome.initiator_id}: {old_trust:.2f} → {new_trust:.2f}",
            ))

    # Record the interaction
    rel.record_interaction(state.tick, positive=outcome.was_positive)

    return events


def _apply_recruitment_outcome(
    state: WorldState,
    outcome: ConversationOutcome,
    agent_specs: dict[str, AgentSpec],
) -> list[Event]:
    """Apply recruitment attempt outcome."""
    events = []

    target_state = state.get_agent(outcome.target_id)
    initiator_state = state.get_agent(outcome.initiator_id)

    if target_state is None or initiator_state is None:
        return events

    if outcome.recruitment_successful:
        # Mark target as recruited
        target_state.is_recruited = True
        state.total_rebels_recruited += 1

        # Both now know each other are rebels
        target_state.known_rebels.add(outcome.initiator_id)
        initiator_state.known_rebels.add(outcome.target_id)

        # Update relationship knowledge
        rel = state.get_relationship(outcome.initiator_id, outcome.target_id)
        rel.a_knows_b_is_rebel = True
        rel.b_knows_a_is_rebel = True

        events.append(Event(
            tick=state.tick,
            event_type=EventType.RECRUITMENT_SUCCESS,
            agent_id=outcome.initiator_id,
            target_id=outcome.target_id,
            details={
                "total_rebels": state.total_rebels_recruited,
            },
            narrative=f"{outcome.target_id} has been recruited to the rebellion by {outcome.initiator_id}!",
        ))
    else:
        events.append(Event(
            tick=state.tick,
            event_type=EventType.RECRUITMENT_FAILED,
            agent_id=outcome.initiator_id,
            target_id=outcome.target_id,
            details={
                "target_suspicion_of_initiator": outcome.suspicion_raised,
            },
            narrative=f"{outcome.initiator_id}'s recruitment attempt on {outcome.target_id} failed",
        ))

    return events


def _apply_interrogation_outcome(
    state: WorldState,
    outcome: ConversationOutcome,
    agent_specs: dict[str, AgentSpec],
) -> list[Event]:
    """Apply interrogation outcome."""
    events = []

    target_state = state.get_agent(outcome.target_id)
    if target_state is None:
        return events

    for info in outcome.information_revealed:
        # Add to interrogator's knowledge
        initiator_state = state.get_agent(outcome.initiator_id)
        if initiator_state:
            initiator_state.known_information.add(info)

        # Check if rebellion was exposed
        if "rebel" in info.lower() or "rebellion" in info.lower():
            # This is a major event
            events.append(Event(
                tick=state.tick,
                event_type=EventType.SUSPICION_RAISED,
                agent_id=outcome.target_id,
                details={
                    "information": info,
                    "revealed_to": outcome.initiator_id,
                },
                narrative=f"{outcome.target_id} revealed sensitive information: {info}",
            ))

    events.append(Event(
        tick=state.tick,
        event_type=EventType.INTERROGATION,
        agent_id=outcome.initiator_id,
        target_id=outcome.target_id,
        details={
            "information_count": len(outcome.information_revealed),
            "information": outcome.information_revealed,
        },
        narrative=f"{outcome.initiator_id} interrogated {outcome.target_id}, learned {len(outcome.information_revealed)} pieces of information",
    ))

    return events


def _apply_suspicion_from_conversation(
    state: WorldState,
    outcome: ConversationOutcome,
) -> list[Event]:
    """Apply suspicion raised during conversation."""
    events = []

    # Suspicion typically falls on the initiator (they said something suspicious)
    initiator = state.get_agent(outcome.initiator_id)
    if initiator:
        old_suspicion = initiator.suspicion_level
        initiator.adjust_suspicion(outcome.suspicion_amount)

        events.append(Event(
            tick=state.tick,
            event_type=EventType.SUSPICION_RAISED,
            agent_id=outcome.initiator_id,
            details={
                "amount": outcome.suspicion_amount,
                "old_level": old_suspicion,
                "new_level": initiator.suspicion_level,
                "witnessed_by": outcome.witnessed_by,
                "source": "conversation",
            },
            narrative=f"{outcome.initiator_id}'s suspicious behavior noticed. Suspicion: {old_suspicion:.2f} → {initiator.suspicion_level:.2f}",
        ))

    return events


def _apply_trade_outcome(
    state: WorldState,
    outcome: ConversationOutcome,
) -> list[Event]:
    """Apply trade outcome."""
    events = []

    if outcome.trade_details is None:
        return events

    initiator = state.get_agent(outcome.initiator_id)
    target = state.get_agent(outcome.target_id)

    if initiator is None or target is None:
        return events

    # Trade details format: {"initiator_gives": {"gold": 5}, "target_gives": {"grain": 3}}
    initiator_gives = outcome.trade_details.get("initiator_gives", {})
    target_gives = outcome.trade_details.get("target_gives", {})

    # Apply initiator's side
    for resource, amount in initiator_gives.items():
        if resource == "gold":
            initiator.gold -= amount
            target.gold += amount
        # Add other resource types as needed

    # Apply target's side
    for resource, amount in target_gives.items():
        if resource == "gold":
            target.gold -= amount
            initiator.gold += amount

    events.append(Event(
        tick=state.tick,
        event_type=EventType.TRADE_COMPLETED,
        agent_id=outcome.initiator_id,
        target_id=outcome.target_id,
        details={
            "initiator_gave": initiator_gives,
            "target_gave": target_gives,
        },
        narrative=f"Trade completed: {outcome.initiator_id} and {outcome.target_id} exchanged goods",
    ))

    return events


def _apply_emotional_changes(
    state: WorldState,
    outcome: ConversationOutcome,
) -> None:
    """Apply emotional state changes from conversation."""
    if outcome.initiator_emotional_state:
        initiator = state.get_agent(outcome.initiator_id)
        if initiator:
            initiator.emotional_state = outcome.initiator_emotional_state

    if outcome.target_emotional_state:
        target = state.get_agent(outcome.target_id)
        if target:
            target.emotional_state = outcome.target_emotional_state


# =============================================================================
# UTILITY FUNCTIONS
# =============================================================================

def can_recruit(
    state: WorldState,
    recruiter_id: str,
    target_id: str,
    agent_specs: dict[str, AgentSpec],
) -> tuple[bool, str]:
    """
    Check if a recruitment attempt makes sense.

    Returns (can_recruit, reason).
    """
    recruiter_spec = agent_specs.get(recruiter_id)
    target_spec = agent_specs.get(target_id)

    if not recruiter_spec or not target_spec:
        return False, "Agent not found"

    # Must be a rebel to recruit
    if recruiter_spec.true_faction != Faction.REBEL:
        return False, "Only rebels can recruit"

    # Can't recruit guards
    if target_spec.public_role.value == "guard":
        return False, "Cannot recruit guards"

    # Check if already recruited
    target_state = state.get_agent(target_id)
    if target_state and target_state.is_recruited:
        return False, "Already recruited"

    # Check trust level
    trust = state.get_trust(target_id, recruiter_id)
    if trust < 0.3:
        return False, f"Insufficient trust ({trust:.2f})"

    return True, "Can attempt recruitment"


def estimate_recruitment_success(
    state: WorldState,
    recruiter_id: str,
    target_id: str,
    agent_specs: dict[str, AgentSpec],
) -> float:
    """
    Estimate probability of recruitment success.

    Based on:
    - Trust level
    - Target's traits (loyalty, courage)
    - Circumstances (location, time, witnesses)
    """
    target_spec = agent_specs.get(target_id)
    if not target_spec:
        return 0.0

    target_state = state.get_agent(target_id)
    if not target_state:
        return 0.0

    # Base probability from trust
    trust = state.get_trust(target_id, recruiter_id)
    base_prob = max(0, (trust - 0.3) / 0.7)  # 0 at trust=0.3, 1 at trust=1.0

    # Modify by target's traits
    from ..core.types import TraitName
    loyalty_to_authority = target_spec.rl_profile.get_trait(TraitName.LOYALTY, 0.5)
    courage = target_spec.rl_profile.get_trait(TraitName.COURAGE, 0.5)

    # High loyalty to authority = harder to recruit
    # High courage = more likely to take the risk
    trait_modifier = (1 - loyalty_to_authority * 0.5) * (0.5 + courage * 0.5)

    # Location modifier (tavern at night is safest)
    location_mod = 1.0
    if target_state.location == Location.TAVERN and state.time_of_day == TimeOfDay.NIGHT:
        location_mod = 1.3
    elif target_state.location in {Location.MARKET, Location.TOWN_SQUARE}:
        location_mod = 0.7  # Too public

    # Witness modifier
    witnesses = len(state.get_nearby_agents(target_id)) - 1  # Exclude recruiter
    witness_mod = max(0.3, 1 - witnesses * 0.15)

    final_prob = base_prob * trait_modifier * location_mod * witness_mod
    return min(1.0, max(0.0, final_prob))
